version: '3.8'

services:
  docvault-postgres:
    image: postgres:16-alpine
    container_name: docvault-postgres
    environment:
      POSTGRES_DB: docvault_db
      POSTGRES_USER: docvault_user
      POSTGRES_PASSWORD: docvault_secure_password
    ports:
      - "5434:5432"
    volumes:
      - docvault_pgdata:/var/lib/postgresql/data

  docvault-minio:
    image: minio/minio:latest
    container_name: docvault-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword2026
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - docvault_s3data:/data

  docvault-api:
    build: .
    container_name: docvault-app
    depends_on:
      - docvault-postgres
      - docvault-minio
    environment:
      PORT: 4000
      DATABASE_URL: postgres://docvault_user:docvault_secure_password@docvault-postgres:5432/docvault_db
      S3_ENDPOINT: http://docvault-minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadminpassword2026
      S3_BUCKET: docvault-archive
    ports:
      - "4000:4000"

volumes:
  docvault_pgdata:
  docvault_s3data:
